
//微信精选（分页加载）
export const ACTION_WEIXIN_NEWS_PRE_FETCH = 'ACTION_WEIXIN_NEWS_PRE_FETCH';
export const ACTION_WEIXIN_NEWS_FETCH_OK = 'ACTION_WEIXIN_NEWS_FETCH_OK';
export const ACTION_WEIXIN_NEWS_FETCH_ERROR = 'ACTION_WEIXIN_NEWS_FETCH_ERROR';